### ISSUE TITLE
Can't see more than 4 Clocks

### ISSUE THREAD

**Issue by AlienDarkCat** [brentengelbrecht/world-clock#2]
Can't see more than 4 clocks on screen, please add a way to scroll down (or adjust the size of the fonts of the clocks). This is especially a problem on smaller screens, like on laptops.
![Screenshot 2024-07-06 203450](https://github.com/brentengelbrecht/world-clock/assets/74044041/72979b90-36d8-4510-8e92-1a8c8b12c0d6)

**Comment by brentengelbrecht** [comment]
Thanks for raising this @AlienDarkCat. Will be addressing this in the next minor release.

**Comment by brentengelbrecht** [comment]
Issue has been fixed in [this release](https://github.com/brentengelbrecht/world-clock/releases/tag/v2.1.0)
